services:
  sandbox:
    build:
      context: .
      dockerfile: Dockerfile
    privileged: true
    cgroup: host
    command: ["serve", "--run-timeout", "10", "--compile-timeout", "10"]
    ports:
      - "8080:8080"
