[tools]
go = "1.26.4"
"aqua:golangci/golangci-lint" = "2.12.2"
"aqua:evilmartians/lefthook" = "2.1.9"
"aqua:hadolint/hadolint" = "2.14.0"

node = "24.14.1"
ruby = "3.4.9"
rust = "1.94.1"
python = "3.14.5"
